---
Greenhouse:
  SimulationSpace:
    # Dimensions of the simulation space. The largest dimension should be exactly 1.
    no_voxel_x: 1
    no_voxel_y: 1
    no_voxel_z: 0.0131
    # oxygen_sample_geometry_path: ./vessel_graph_generation/geometries/slab_oxy_sample_3mm.npy
  d: 0.1
  r: 0.0025
  FAZ_radius_bound: # The FAZ radius is randomly drawn from a normal distribution with these parameters
    - 0.44
    - 0.04
  rotation_radius: 1.05 # The radius from the FAZ center in which to apply the rotation term 
  FAZ_center: # x-y position of the FAZ
    - 0.5
    - 0.5
  param_scale: 3 # Parameter scale used to scale all spatial parameters. 3 means we generate a 3 mm x 3 mm image.
  modes: # List of sequential growth stages. We first develop the superficial vascular complex (SVC), then the deep vascular complex (DVC)
    - name: SVC
      I: 100 # Number of iterations
      N: 2000 # Number of added oxygen sinks (OSs) per iteration
      eps_n: 0.18 # Minimal distance between nodes and OSs [mm] 
      eps_s: 0.135 # Min. distance between OSs [mm]
      eps_k: 0.135 # Satisfaction range of nodes [mm] 
      delta_art: 0.2925 # Distance of perception volume for arterial nodes [mm] 
      delta_ven: 0.2925 # Distance of perception volume for venous nodes [mm] 
      gamma_art: 50 # Angle of perception cone w.r.t. parent for arterial nodes [°]
      gamma_ven: 50 # Angle of perception cone w.r.t. parent for venous nodes [°]
      phi: 15 # Minimal std of attraction vector angles for symetric bifurcation
      omega: 0.3 # Weighting factor optimal growth direction
      kappa: 2.55 # Bifurcation exponent
      delta_sigma: 0.02 # Linear growth rate of simulation space per iter
    - name: DVC
      I: 150
      N: 2000
      eps_n: 0.09
      eps_s: 0.0675
      eps_k: 0.0675
      delta_art: 0.14625
      delta_ven: 0.14625
      gamma_art: 90
      gamma_ven: 90
      phi: 15
      omega: 0
      kappa: 2.9
      delta_sigma: 0.02
output:
  directory: ./vessel_graph_generation/datasets/dataset_18_June_2023 # Output directory
  image_scale_factor: 304 # Number of pixels for the largest image dimension. Final dimensions are calculated based on simulation space dimensions.
  save_trees: true # If true, save the generated vessel graph as a csv file
  save_3D_volumes: null # "null": Do not save 3D volume, "npy": Save as numpy array, "nifti": Save as NIFTI file
  save_2D_image: true # If true, save the pixelized Maximum intensity projection along the proj_axis
  proj_axis: 2 # Axis alogn which to calculate the MIP for 2D image generation
  save_stats: true # Save statistics about growth process
Forest:
  type: stumps # Initialize forest by tree stumps at the faces of the 3D volume
  source_walls: # Faces along wich to place the initial tree stumps
    x0: true
    x1: true
    y0: true
    y1: true
    z0: false
    z1: false
  N_trees: 8 # Number of separate trees that are grown simultanously
  nerve_center: [0.43,0.88] # If type is set to nerve, this is the x-y position of the nerve
  nerve_radius: [0.01] # Radius of the optical nerve
